### ISSUE TITLE
sonarjs ts rules

### ISSUE THREAD

**Issue by OneCyrus** [SonarSource/eslint-plugin-sonarjs#142]
**I want to request a feature.**

currently we are using the sonar tslint plugin. now that tslint is deprecated we would like to migrate to eslint. this plugin here looks nice but it is missing a lot of the rules we used in tslint. but there is another repo here (sonarjs) which has almost all those rules. but it is a sonar plugin. 

my question is now if this eslint plugin here will add the rules from sonarjs as well or what is the story going forward? a native eslint pluging would help us a lot. the java overhead from sonarjs is not that great for the dev experience.

**Comment by vilchik-elena** [comment]
we plan to gradually migrate rules from sonarjs to this native eslint plugin. We already moved 4 rules (#44, #90, #50, #80) and will release today/tomorrow.

As we are SonarSource developers, SonarJS (used inside SonarQube) is our primary project, that's why you don't yet see all rules here.

I hope we will move most of the rules by the end of the year (and feel free to contribute).
