### ISSUE TITLE
Plugin available in the form of a .jar package

### ISSUE THREAD

**Issue by Malgosiatobiasz1** [SonarSource/eslint-plugin-sonarjs#440]
Hi, is it possible to make this plugin available for download as a .jar package?

**Comment by yassin-kammoun-sonarsource** [comment]
Hello @Malgosiatobiasz1,

Thank you for reaching out with your question!

This repository is designed as a standard Node.js package published on NPM, specifically crafted to function as an ESLint plugin. In the current context, introducing a JAR file doesn't align with the intended purpose.

Could you kindly elaborate on the specific scenario or use case where a JAR file might be beneficial? Your insights will help us better understand your needs and explore potential enhancements.

Thank you!

**Comment by Malgosiatobiasz1** [comment]
Hi @yassin-kammoun-sonarsource I am implementing sonarqube using a helm chart https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube-dce/values.yaml   and I can install plugins from jar packages only(lines 274-282)

   # List of plugins to install.
  # For example:
  # plugins:
  #  install:
  #    - "https://github.com/AmadeusITGroup/sonar-stash/releases/download/1.3.0/sonar-stash-plugin-1.3.0.jar"
  #    - "https://github.com/SonarSource/sonar-ldap/releases/download/2.2-RC3/sonar-ldap-plugin-2.2.0.601.jar"
  #
  plugins:
    install: []

**Comment by yassin-kammoun-sonarsource** [comment]
Thank you for the clarification!

As mentioned earlier, this repository is a Node.js project, making it unfeasible to provide a JAR file for it. Nevertheless, the rules embedded in this ESLint plugin are also accessible through [SonarJS](https://github.com/SonarSource/SonarJS), the JavaScript analyzer within SonarQube, available in all editions of the product.

Given that SonarJS is a Maven project, you can locate the corresponding JAR file in the [Maven Repository](https://mvnrepository.com/artifact/org.sonarsource.javascript/sonar-javascript-plugin). However, I don't think you actually need to do anything since SonarJS is shipped with SonarQube, but I could be wrong as I am not an expert for the particular case of SonarQube Helm Chart.

If this information doesn't fully address your needs, I highly recommend seeking assistance at https://community.sonarsource.com/. There, you'll find experts on the SonarQube Helm Chart who will be more than willing to assist you.

Hope this proves helpful!

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-32](https://sonarsource.atlassian.net/browse/ESLINTJS-32)
